### PR TITLE
[PE188-72] Fix issues Milestone 1

### PR DESCRIPTION
**Pull request by LeonardoSantis-AcidLabs**
## Link to Issue(s) in JIRA:
- https://linets.atlassian.net/browse/PE188-72

## Description

Fix related issues to the revision of the first milestone
https://github.com/Departamento-TI/cenabast-tienda/issues/47

- Update elasticsearch-oss 7.10.2 for elasticsearch 8.12.2
- Add logout behaviour to actually call the Keycloak distribution /logout endpoint (end session in keycloak too)
- Re added store preference, in order to facilitate admin users inpersonation of stores
- Remove unique email validatios, add unique run validatios (for Spree::User)
- Buttons on header profile menu now actually redirect to related Spree pages (cart, my account)
- Add specs/docs for changes in components, models, and new services
- Add docs

## Checklist

Before you move on, make sure that:

- [x ] No unintended changes are included
- [x ] Spelling is correct
- [x ] There are tests covering new/changed functionality
- [x ] Rubocop style is passing, and Rspec tests are passing.
- [x ] Documentation has been written (Docs or code)
- [x ] Commits have meaningful names and changes. _CR remarks_-like commits are squashed.
- [x ] Proper labels assigned. Use `WIP` label to indicate that state

### CODE REVIEW

**Comment by nmella** [comment]
No estoy seguro, pero me parece que también ¿habría que [eliminar la versión](https://github.com/Departamento-TI/cenabast-tienda/blob/721b5195cf2c01029112eda9ae4f8df14c00bcc0/Gemfile#L167) de la gema de elasticsearch o no ?

```
gem 'elasticsearch', '< 7.14'
```

**Comment by LeonardoSantis-AcidLabs** [comment]
> No estoy seguro, pero me parece que también ¿habría que [eliminar la versión](https://github.com/Departamento-TI/cenabast-tienda/blob/721b5195cf2c01029112eda9ae4f8df14c00bcc0/Gemfile#L167) de la gema de elasticsearch o no ?
> 
> ```
> gem 'elasticsearch', '< 7.14'
> ```

Hola Nicolas,

Ciertamente, gracias por el comentario
Ya cambie la versión de la gema tambien a 8.12.2.

**Comment by LeonardoSantis-AcidLabs** [comment]
Voy a mergear el PR. Cualquier detalle extra que surja puedo abrir uno nuevo

**Comment by nmella** [comment]
Perfecto, gracias Leo. Haré las pruebas y te comento.

**Pull request merged**
